### ISSUE TITLE
Error message improvement for: unknown option '-P' for command '-a'

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#103]
Hello,

in my test cases, the command line option `-P` is mostly used in Bash scripts, which append a directory after `-P` from a Bash variable. Example:

```Bash
ghdl -a -P$PrecompiledDir --work=$Library $SourceFile
```

If there is an error in the Bash file, it could happen that `$PrecompiledDir` is empty. So `-P` is passed to GHDL without any data/path. In this case GHDL reports: `unknown option '-P' for command '-a'`.

I think the message could be improved to something like `path expected after option -P`, because `-P` is a valid option for `-a`, but it's empty.

Regards
    Patrick

**Comment by tgingold** [comment]
Make sense.
