### ISSUE TITLE
Is is possible to compile the git-hash or date into the development version?

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#12]
This is a feature request.

I compiled GHDL again and saw that the embedded date of 0.34dev is not the compile date. I think it would be nice for bug reporting to know the exact git-commit from which GHDL was compiled. So you can track if one reports bugs on a none up-to-date version.

How could it be solved?
GCC knows -D to pass defines into the compiler. The makefile and the Windows PoSH script could assemble a define based on:

- the short git-hash of HEAD
- the commit date of HEAD
- the current git branch
- the current date
- other data?

This should only be included in development builds.

Example:
GHDL 0.34dev - build from branch 'paebbels/master' (4742afe63) - 04.01.2015

Regards
    Patrick

**Comment by tgingold** [comment]
On 04/01/16 20:08, Patrick Lehmann wrote:
> This is a feature request
>
> I compiled GHDL again and saw that the embedded date of 034dev is not
> the compile date I think it would be nice for bug reporting to know the
> exact git-commit from which GHDL was compiled So you can track if one
> reports bugs on a none up-to-date version

In fact this is not that important to me.
In case of report, I try to reproduce the issue.  If I can, I try to fix 
it.  If I cannot, I simply add it in the testsuite.


> How could it be solved?
> GCC knows -D to pass defines into the compiler The makefile and the
> Windows PoSH script could assemble a define based on:
>
>   * the short git-hash of HEAD
>   * the commit date of HEAD
>   * the current git branch
>   * the current date
>   * other data?
>
> This should only be included in development builds
>
> Example:
> GHDL 034dev - build from branch 'paebbels/master' (4742afe63) - 04012015

The build scripts can modify version.ads if needed.

Tristan.
