### ISSUE TITLE
ld: cannot find -lz 

### ISSUE THREAD

**Issue by RGNagel** [tgingold/ghdl#122]
I was followed the tutorial "Starting with GHDL and I got stuck at:
$ ghdl -e -v hello_world
and it printed out:
"
/usr/bin/gcc -o hello_world e~hello_world.o /usr/lib/ghdl/v93/std/std_standard.o /usr/lib/ghdl/v93/std/textio.o /usr/lib/ghdl/v93/std/textio_body.o hello.o /usr/lib/ghdl/libgrt.a -ldl -lm -Wl,--version-script=/usr/lib/ghdl/grt.ver -Wl,--export-dynamic -L./ -lz
/usr/bin/ld: cannot find -lz 
collect2: error: ld returned 1 exit status
ghdl: compilation error
"

I installed Ghdl by binary package and I assured I had installed all dependences. Also, I've followed exactly the same steps as the tutorial.
System: Debian GNU/Linux 8 (jessie) 32-bit.

Let me know if I did not provide enough information.

**Comment by tgingold** [comment]
On 24/07/16 03:56, Rafael Nagel wrote:
> I followed the tutorial "Starting with GHDL" (
> <http://ghdl.readthedocs.io/en/latest/Starting_with_GHDL.html#the-hello-world-program>
> )
> and I got stuck at:
> $ ghdl -e -v hello_world
> and it printed out:
>
>                                     /usr/bin/gcc -o hello_world
>                                     e~hello_world.o
>                                     /usr/lib/ghdl/v93/std/std_standard.o
>                                     /usr/lib/ghdl/v93/std/textio.o
>                                     /usr/lib/ghdl/v93/std/textio_body.o
>                                     hello.o /usr/lib/ghdl/libgrt.a -ldl
>                                     -lm
>                                     -Wl,--version-script=/usr/lib/ghdl/grt.ver
>                                     -Wl,--export-dynamic -L./ -lz
>                                     /usr/bin/ld: cannot find -lz
>                                     collect2: error: ld returned 1 exit
>                                     status
>                                     ghdl: compilation error
>                                     <<<<<<<<<
>
> I installed Ghdl by binary package and I assured I had installed all
> dependences.
> System: Debian GNU/Linux 8 (jessie) 32-bit.

You need to install zlib1g-dev

Tristan.

**Comment by RGNagel** [comment]
Thanks for the fast and right reply, Tristan. It worked like a charm.

**Comment by tgingold** [comment]
On 24/07/16 07:51, Rafael Nagel wrote:
> Thanks for the fast and right reply, Tristan. It worked like a charm.

Great!
