### ISSUE TITLE
New documentation section for the "wave-opt-file" format.

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#138]
Hello,

GHDL got a new file format for wave option files: `--wave-opt-file=<FILENAME>`.
Please add an additional section to the [GHDL documentation](http://ghdl.readthedocs.io/en/latest/index.html) and link it to the [command line option](http://ghdl.readthedocs.io/en/latest/Simulation_and_runtime.html#cmdoption--wave-opt-file).

**Supported formats (from ghdl-discuss):**
```
# comment
top_level_instance/signal1
top_level_instance/sub_entity_a_instance/*
```

*Please add more formats, while an official format documentation is missing.*

**Edit:** pull request #135 adds a basic documentation

**Comment by Jonsba** [comment]
Hello Patrick,
I have already made a pull request which includes improved documentation. Only the currently supported formats are documented, new formats will be described once they are supported.
