### ISSUE TITLE
Error in `ghdl --help -r` output

### ISSUE THREAD

**Issue by pacalet** [tgingold/ghdl#146]
```
$ ghdl --version
GHDL 0.34dev (20151126) [Dunoon edition]
 Compiled with GNAT Version: 4.9.2
 llvm code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2015 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ ghdl --help -r
-r UNIT [ARCH] [OPTS]      Run UNIT
...
```
should probably be:
```
$ ghdl --help -r
-r [OPTS] UNIT [ARCH]      Run UNIT
...
```

**Comment by tgingold** [comment]
Simulation options are after unit name.
OTOH, it is possible to have some options before in some cases, but that's almost useless.

I don't think I will change this help line.

**Comment by pacalet** [comment]
I see. But when using the mcode backend one must pass elaboration options too. Example:

```
$ ghdl --version
GHDL 0.34dev (20151126) [Dunoon edition]
 Compiled with GNAT Version: 4.9.2
 mcode code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2015 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ghdl -r counter --std=08 --ieee=standard --work=counter_lib --workdir=counter_lib/lib -Pcounter_lib/lib
ghdl: cannot find entity or configuration counter
$ ghdl -r --std=08 --ieee=standard --work=counter_lib --workdir=counter_lib/lib -Pcounter_lib/lib counter
... (simulation OK) ...
```
Perhaps should there be a different help for mcode?

**Comment by tgingold** [comment]
On 31/08/16 11:51, pacalet wrote:
> I see. But when using the mcode backend one must pass elaboration
> options too. Example:
>
> |$ ghdl --version GHDL 0.34dev (20151126) [Dunoon edition] Compiled with
> GNAT Version: 4.9.2 mcode code generator Written by Tristan Gingold.
> Copyright (C) 2003 - 2015 Tristan Gingold. GHDL is free software,
> covered by the GNU General Public License. There is NO warranty; not
> even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. $ ghdl -r
> counter --std=08 --ieee=standard --work=counter_lib
> --workdir=counter_lib/lib -Pcounter_lib/lib ghdl: cannot find entity or
> configuration counter $ ghdl -r --std=08 --ieee=standard
> --work=counter_lib --workdir=counter_lib/lib -Pcounter_lib/lib counter
> ... (simulation OK) ... |
>
> Perhaps should there be a different help for mcode?

Like this ?

$ ./ghdl_llvm -h -r
-r UNIT [ARCH] [OPTS]      Run UNIT
Main options (try --options-help for details):
[...]

$ ./ghdl_mcode -h -r
-r,--elab-run [OPTS] UNIT [ARCH] [RUNOPTS]  Run UNIT
Main options (try --options-help for details):
[...]

**Comment by pacalet** [comment]
Yep, that would be fine, I think.

**Comment by tgingold** [comment]
On 31/08/16 15:27, pacalet wrote:
> Yep, that would be fine, I think.

So, the current output is fine !

**Comment by pacalet** [comment]
Hmm. Sorry then, I must have done something wrong during the install. I have nothing like these executables installed. Forget this issue, I must read the install instructions once more. Thanks for your answer.

**Comment by tgingold** [comment]
On 01/09/16 07:39, pacalet wrote:
> Hmm. Sorry then, I must have done something wrong during the install. I
> have nothing like these executables installed. Forget this issue, I must
> read the install instructions once more. Thanks for your answer.

ghdl_mcode and ghdl_llvm are what I build for development.

Still, the idea of supporting --work and --workdir for llvm/gcc is a 
good idea.
