### ISSUE TITLE
GHDL compile error

### ISSUE THREAD

**Issue by jbnote** [tgingold/ghdl#156]
Hi,

The following code ([compile_error_vhd.txt](https://github.com/tgingold/ghdl/files/496645/compile_error_vhd.txt)) triggers a compilation error like this:
`compile_error_vhd.txt:58:34: can't match 'ret_split_t' with type the anonymous integer subtype defined at compile_error_vhd.txt:42:31`

Other tools, quartus, ncsim, vsim and synthesizers were handling this correctly four years ago, and i'm not really able to find out in the LSM the relevant part which would void such code, so i'm relying on your expertise to qualify this as a bug or not (I can understand that the types are not directly related and probably should be, while i'm just using them as shorthand for integer ranges, which are working correctly on their own).

**Comment by tgingold** [comment]
This was a bug.  Very surprising that nobody noticed it before as the reproducer doesn't look very particular.  Thank you again for the report; I will commit the fix soon.
