### ISSUE TITLE
build procedure with download_prerequisites and --with-gmp=/usr/local doesn't work

### ISSUE THREAD

**Issue by wfjm** [tgingold/ghdl#159]
Just tried a build with gcc backend from current master  commit 8b090b01da269679e98a578f4fda17e3e4adce12 .

Followed the updated BUILD.txt, did

    ...
    ./contrib/download_prerequisites
    ...
    ../gcc-4.9.3/configure --prefix=$PREFIX ... --with-gmp=/usr/local

That leads to an abort with

    checking for gmp.h... no
    configure: error: gmp.h can't be found, or is unusable.

Leaving out  `--with-gmp=/usr/local` fixes this.

My understanding is that `--with-gmp=/usr/local` is incompatible with `download_prerequisites` because gmp is one of the downloaded prerequisites and thus certainly not under `/usr/local`.

With best regards,  Walter

**Comment by tgingold** [comment]
You're correct, I will adjust the instructions.
