### ISSUE TITLE
conditional assignment in a process not supported

### ISSUE THREAD

**Issue by JimLewis** [tgingold/ghdl#17]
## Issue
Conditional assignment is a process not supported
## Test Case
[cond_assign_proc.txt](https://github.com/tgingold/ghdl/files/79342/cond_assign_proc.txt)
## Impact
In OSVVM testbench.  Changing testbench to make it a non-issue.

**Comment by tgingold** [comment]
On 06/01/16 04:26, JimLewis wrote:
>
>     Issue
>
> Conditional assignment is a process not supported

So that's for both signals and variables, isn't it ?

**Comment by JimLewis** [comment]
Yep.

**Comment by tgingold** [comment]
Now implemented.

Tristan.
