### ISSUE TITLE
Exeeeding 2**31

### ISSUE THREAD

**Issue by JimLewis** [tgingold/ghdl#19]
## ISSUE
What should a simulator do if we add 2**30 + 2**30?

Particularly since the language specifies the range of integer to be the minimum supported

## GHDL crashes with the following:
c:\tools\ghdl-0.33\bin\ghdl.exe:error: overflow detected
c:\tools\ghdl-0.33\bin\ghdl.exe:error: simulation failed

## Other potential behavior
I have seen other behavior that allows the integer to quietly roll over.  The nice side to this is that it returns control to the user program for handling the numbers

## Test case
[integer_max_val.txt](https://github.com/tgingold/ghdl/files/80604/integer_max_val.txt)

## Impact
In weighted distributions (DistInt), I check to see that the sum is non-decreasing.  This makes it easy to check for either a negative number or roll-over, and hence, do some sensible error reporting.  OTOH, having the tool crash will communicate that the user did something wrong.  

Oh how I wish we had conditional compilation for the testbenches that allowed me to test for simulator name.

**Comment by tgingold** [comment]
LRM2008 5.2.3.1 is very  clear about that issue:

The same arithmetic operators are predefined for all integer types (see 9.2). It is an error if the execution of such an operation (in particular, an implicit conversion) cannot deliver the correct result (that is, if the value corresponding to the mathematical result is not a value of the integer type).

The mathematical result of 2**30 + 2**30 is 2**31 which is not a value of the Integer type.

I don't think we want conditional compilation to test for simulator name as this is a no end work.  We'd better to have a very precise LRM and then compliant tools.

Tristan.
