### ISSUE TITLE
Jumps.c errors when cross native compiling to Mingw

### ISSUE THREAD

**Issue by imd1** [tgingold/ghdl#23]
I'm attempting to cross native build ghdl with gcc backend (Cygwin build, Mingw host/target), and make errors when trying to compile jumps.c. The first error involves siginfo_t not being defined.  Googling reveals that mingw may not support siginfo_t.  In order to work around this temporarily, I've deleted the contents of jumps.c, and the build proceeds, but I suspect I may hit a run time issue at some point.

Can anyone help with a) a way of keeping the content of jumps.c and b) whether omitting its content will work going forwards

**Comment by tgingold** [comment]
On windows, src/grt/config/win32.c should be used instead of src/grt/config/jumps.c

Tristan.

**Comment by imd1** [comment]
Presumably this means that there is a bug in a make file?

**Comment by tgingold** [comment]
On 20/01/16 10:32, imd1 wrote:
> Presumably this means that there is a bug in a make file?

Yes.  Cross-compilation was never tried and may require
some adjustments (in particular in src/grt/Makefile.inc).

Tristan.
