### ISSUE TITLE
Possible to get list of all instances with elaborated generic parameters?

### ISSUE THREAD

**Issue by benreynwar** [tgingold/ghdl#282]
Is it possible to get elaboration information from ghdl?

For example, I have a top level design, which contains many instances of the 'Memory' module but with different 'width' and 'depth' generic parameters.  It would be very useful to be able to get all the (width, depth) pairs that are instantiated so that I could use this information to automate the generation of the compiled memories.

Is this currently possible?  If not, would it be difficult to implement, and what would the best way to go about it be?

**Comment by Paebbels** [comment]
You can use cuncurrent assert statements to print the passed parameters.

**Comment by benreynwar** [comment]
Ah, great idea!  Thank you!
