### ISSUE TITLE
Make `configure` select the right ortho-lang.c according to the gcc version

### ISSUE THREAD

**Issue by 1138-4EB** [tgingold/ghdl#292]
From #280 

> [1138-4EB] Since the content of BUILD.txt is moved to the docs, what shall we do with this line?
gcc version 6.3 [do not modify this line as this is read by scripts].

> [Paebbels] Can we move this security check to configure and maybe also integrate the switching of ortho-lang.c based on the configured / found GCC version?

> [tgingold] Yes, we should select the right ortho-lang.c according to the gcc version.

**Comment by tgingold** [comment]
Now implemented.
