### ISSUE TITLE
Generic fancy ZIP/TGZ shields

### ISSUE THREAD

**Issue by 1138-4EB** [tgingold/ghdl#308]
I'm trying to create fancy shields for the 'Releases' section in the new documentation: http://ghdl.readthedocs.io/en/new-documentation-structure/getting/Releases.html

These are some options:

![](https://img.shields.io/badge/ZIP-ghdl--0.34--dev--llvm--3.8--2017--03--01--ubu1204-323131.svg?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAACXBIWXMAAAztAAAM7QFl1QBJAAAAB3RJTUUH4QMFFTkX9giBgwAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAACSklEQVRYw9WWPWhUURCFvxOCCioiMbFRcFHRFBrBgAiChcIWCjbaCSKIYBoFK4uApjRYBCEixGApQRDRzkLFH0QLi2hhsYWFEFCxiMUasntsZvX52Oy%2B%2FcfTvDuXe9%2BcO3fumYEUbOdtl9waJsgIVSFwF9gKXAH6aQxF4CGwBTgn6U69DdUclIHvkt7SBGwXYzhjuyDpWa31fXQWT23vsN0zAgAfgQ0rkegGgVXAJ0DVSHSDAMBm4L0k0iQ6QWCllzNi%2B7qkTItbwVFgJ5A8agkYBwazsm0akgpAocrzPJ8i9e8VpO7GHYiMq%2FlSYmIbMAYci8g8bmOOlIHjwHL8dxr4LOmvFLuWWjR2SmW8Kv25Atu5GmsntQKAB8DrGA%2BF85dAf2rdQeBDKidyWZNwwPauxMkWJX2pPC1gIVXYipJKttcDp%2BP9vwH22P4JrK1WQHINlNrtsWci7FdhD4X9JOzhxJ79MTeTmMs1I0SXJBUiIuMN7FuK75pWpPidpKkYP8%2BwfgG4ChySNB9zJ1sRoiMRxunQ9npZ%2FgO4FntGgHvA6mYJnJK0aPsAcCFjY7IbmK%2FnIwuBR5Lux3gsWq4K9jVZmBoicDYR1jOpU94C9iYKTlJyy42UzloqOJno89KqdxjYaPsmsC7mh8MeyFIbklL8FdjUpQblm6TBdDHqA04AFyNbb7SxXC8Dl4FfwFTkUTndnFQiMWt7ru212J6zPdurnrCnbfn%2FSaCjLVk9IeoDRm3fztrdZHQ%2BCrzIkq1520tuP5Zs59P%2BfgMZ9cSNteEU5AAAAABJRU5ErkJggg%3D%3D)
![](https://img.shields.io/badge/ZIP-ghdl--0.34--dev--llvm--3.8--2017--03--01--ubu1204-323131.svg?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAMgAAADwCAMAAAByr9tsAAAC5VBMVEXw8PDx8fHy8vLz8%2FP09PT19fX29vb39%2Ff5%2Bfn6%2Bvr7%2B%2Fv8%2FPz9%2Ff3%2B%2Fv7%2F%2F%2F8QEBARERESEhITExMUFBQVFRUWFhYXFxcYGBgZGRkaGhobGxscHBwdHR0eHh4fHx8gICAhISEiIiIjIyMkJCQlJSUmJiYnJycoKCgpKSkqKiosLCwtLS0uLi4vLy8wMDAxMTEzMzM0NDQ1NTU2NjY3Nzc4ODg5OTk6Ojo8PDw9PT0%2BPj4%2FPz9AQEBBQUFCQkJDQ0NERERFRUVGRkZHR0dISEhJSUlKSkpLS0tMTExNTU1OTk5PT09QUFBRUVFSUlJTU1NUVFRVVVVWVlZXV1dYWFhZWVlaWlpbW1tcXFxdXV1eXl5gYGBiYmJjY2NkZGRlZWVmZmZnZ2doaGhpaWlqampra2tsbGxtbW1ubm5vb29wcHBxcXFycnJzc3N0dHR1dXV2dnZ3d3d4eHh5eXl6enp7e3t8fHx9fX1%2Bfn5%2Ff3%2BAgICBgYGCgoKDg4OEhISFhYWGhoaHh4eIiIiJiYmKioqLi4uMjIyNjY2Pj4%2BQkJCRkZGSkpKTk5OUlJSVlZWWlpaXl5eYmJiZmZmampqbm5ucnJydnZ2enp6fn5%2BgoKChoaGioqKjo6OkpKSlpaWmpqanp6eoqKipqamqqqqrq6usrKytra2urq6vr6%2BwsLCysrKzs7O0tLS1tbW2tra3t7e4uLi5ubm6urq7u7u8vLy9vb2%2Bvr6%2Fv7%2FAwMDBwcHCwsLDw8PExMTFxcXGxsbHx8fIyMjJycnKysrLy8vMzMzNzc3Ozs7Pz8%2FQ0NDR0dHS0tLT09PV1dXW1tbX19fY2NjZ2dna2trb29vc3Nzd3d3e3t7f39%2Fg4ODh4eHi4uLj4%2BPk5OTl5eXm5ubn5%2Bfo6Ojp6enq6urr6%2Bvs7Ozt7e3u7u7v7%2B%2Fw8PDx8fHy8vLz8%2FP09PT19fX29vb39%2Ff4%2BPj5%2Bfn6%2Bvr7%2B%2Fv8%2FPz9%2Ff3%2B%2Fv7%2F%2F%2F%2F8Y6L6AAAAFnRSTlMAAAAAAAAAAAAAAAAAAAAiRGaIqszuJ67%2FqwAAB0lJREFUeAHt3X141WUdx%2FE90Blj53yYbJPJkIeBKDmBlSSgtK0AKxoQCyvMQCW0bEFYIfQAaC1LYLmZaakNca4AC9BqKQZRIjpQeQAnDMYDJCwZsJ19%2Fu4KOdsZv%2Fuc3330XJ3v%2Fbvu19%2B%2F88f7Otfvur73Od%2FrupMYfzx%2FfP%2Fr9Q%2FfXZQNF%2BmIG0VI%2FHT8a%2FHHAogi8I1CgSFqu%2BamIrK0Tb%2FuKzBE7d1lUVJyjp6eGxAYotb0RUQ0hXxxqNAQhfVZiORJ8sy3M0wJYWMhIsg%2BTXJzvikhPDsdEXyXJE9%2FxZQQtpdBzXeA%2F%2FNUsuwQjZI5vGDfaENCeG40lHzHeMH5uw0JYVNfKC3mRatSzQjhJj9Uss%2Fyop3XmBHCb0FpNUNayswIeW8wVCawy1K%2FCSHcABX%2FQXZZk2JCCIug8lOG2ZFvQshWqHyC4U4UGxDCyVAIHGK4ttkGhGyASiW7eyDw%2FwxBVFQLDoDCZ3mJWp%2F0EC6GQmaQl9iSIz3kHT8UXuOl9l8lPIQToPAQHY4VCg%2BphcI0OrUUyw45nwKny6lwbrroEN4MhTepEJwjOqQCCtVUWiQ55BUo3Ea1lX65IcFMON3ACJ7uqR0iYt7KZCTPp4oN%2BTkUmhnJP7OlhrwKhb8yojdyhYa0%2BtUDcERv9ZMZwsFwuotR7OkvM2QinIoZzb4BIkPugdMARtU4WGLIw3BKY3QHhggMqYfCKUbXNExeyGEo7Hb91HA5I0pITzi9TDdHrhUXkgun39PVsRHSQq6FUxXdnSgQFjIeTj%2BihqPXyAr5Apy%2BSR2HhooKuRNOd1DLOwMlhSyE063Usy9PUMiDcJpBTW%2FlyAlZCafp1PVqbzEh1cpvRNumjyhCEuIxOH2Z%2Btb3FBLyhPpl1%2FdMhoyQVbEdERWqZITUwmkhY%2FIDESF%2FgFMFY3OHhJBn4PQUYxMsFfqyv0TyPzvXV%2F1w3u0zPl86ZWrZ1xetePovDc1tjKB1bOJDfgWnykWf6w%2BFwJU3L3jytXN0Ojks4SErEKtew8vu%2F0c7u9ubneiQCnwgSZMf2sFwW3wJHlF%2BjA8s90u%2FPcVOz%2FoTG%2FI9fBhp0%2BrO8qKfiDpYxa73bX8O8oKZCQ0pw4d3xcJDJHl2dCJDShAP6bdsJXk4L4EhoxAnn95EvuJLXMggxE3xNj6WuJBkxI%2F%2F1qbZiQo5g7hKfnBUgkL2Is6uTGJCvIR4S1DI77wS8oBXQu70SsgEr4QM9UhIezocAj0uHzJybNEnx984buyYkYMy%2FSaE7EKnrDEzyn9W87fdp4LsruNU4%2FZ1K8qnjMwUHLIGAPp%2BZt6jL5%2Bgu5Mv3D9toMyQX4wpX93ImBz704KPylgFjIPGlZPSjAxROLPqRjNDFHbeleSNEPK9RwZ6I4RsXZbsjRDyyO0Z3gghG67zSAjPzPRICFnZ0yMh3NJPHWKeN%2Ft4JIR%2F93kkhGsyPBLCaq%2BE8BavhBzP8UgIH%2FVKSNsQj4TwN14Jac00ckRRmOOVkBe9EnK%2Bh0dCONErId%2F3SsgTXgnZ6pWQt70ScsIrIeeS6BE2xIbYEBsilQ0RwIbIH1FsiA1RsyE2xIbYEBsigA2xITbEhtgQAWyIDTmAqA4YE1KHqOqMCbkXUd1rTEgJoioxJuQyRHWZKSF74GKPISE1cFFjSEg5XJQbEjIOLsaZERJMgYuUoBEhO%2BBqhxEhj8PV40aEzIWruUaEXA9X15sQ0pYGV2ltBoRsg4ZtBoRUQ0O1ASGzoGGWASEjoGGE%2FJDWdGhIbxUfshlaNosPWQ4ty8WHzISWmeJDhkPLcOkhLX5o8bcID6mHpnrhIRXQVCE8pAyayoSH5ENTvuyQk9B2UnTIRmjbKDpkCbQtER1SCm2lokPyoC1PckgzYtAsOGQtYrBWcMh9iMF9gkMmIQaTBIfkIAY5ckMaEZNGsSG1cEoZcdPk0uKPZ8GpVmzId9Bd9lef3d%2FB9x3deE8%2BulsgNqQI4UbVBdld%2FacQrkhqSEdvdOm9igov5IY%2F0iE0ZBe6FOyn0tEb0GWX0JAadOrfxAiOD0WnGqEh89Fps9bfDvOFhpTobZtMUD8mKOQqhKzWu6lqmNCQPghpYBTbEZIlNCQDIS16P1D0EhrSAyG79RYKUoWG5OqdmeoQcoXQkEKETNO73r9QaMjXEBJ4nRFtCyBkltCQKnTKb2YEhwehU7XQkOYMdLpuL5X2FqBTxhGhISxGl9TqdjoEH0lBlxJKDdmAcINX%2FJvdvFuZj3DPiw3hWHTTa9zSde8fETve%2FuOym3qpFwIlhuz0wcGfnJeX5IeD7w3BIayEtl9ScgjnQdN8Cg7RLwnMp%2FQQru0DV1nrKD%2BEB90XmA%2FShBC2V12NKK6ubqe8ELWO54oRQfFzHaTMELWGJROTcImkiUsbSAoOUQtuXz576viCfj5fv4LxU2cv3x4kKT9EKhtiQ2yIDbEhNsSG2BAbYkNsiA2xITbEhtgQG2JDbIgNsSE2RKz%2FAnETVxXeh4p1AAAAAElFTkSuQmCC)
![](https://img.shields.io/badge/ZIP-ghdl--0.34--dev--llvm--3.8--2017--03--01--ubu1204-323131.svg?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAACE1BMVEUAAAAAAABcXFwAAACpqakAAABXV1cAAAAAAADAwMBYWFgAAACcnJxzc3MiIiKPj4%2FExMRaWlohISHo6OgbGxs5OTnMzMw9PT3AwMBWVlZkZGSGhoanp6eLi4vMzMyAgIC3t7eUlJSysrKNjY2Wlparq6uysrKlpaW1tbV6enqzs7PR0dGrq6uEhISwsLDFxcW9vb3Kysrg4OC8vLy3t7fPz8%2FDw8Ojo6OsrKzS0tLQ0NC9vb3ExMTm5ua9vb3Q0NChoaGsrKyurq7e3t7U1NSWlpaJiYmNjY3R0dG0tLSVlZXCwsK8vLzDw8Ph4eHk5OTW1tbW1tbm5ube3t7g4ODKysq3t7fOzs7f39%2FW1tbR0dHOzs7CwsLe3t7c3Nzn5%2BfW1tbq6urIyMjb29vW1tbe3t7X19fa2trb29vt7e3q6urHx8ft7e3k5OTh4eHPz8%2FV1dXT09Pm5ubh4eHg4ODm5ub9%2Ff3%2F%2F%2F%2F%2F%2F%2F%2Fk5OTp6enY2Njo6OjZ2dnn5%2Bfp6enc3Nzu7u76%2Bvr09PTk5OTw8PDn5%2Bf5%2Bfnf39%2Fq6urg4ODo6Ojk5OT4%2BPjm5ubm5ubs7Ozu7u76%2Bvrk5OTu7u739%2Ffq6urr6%2Bvx8fH6%2Bvrt7e34%2BPj6%2Bvr%2B%2Fv7s7Oz5%2Bfn%2B%2Fv7%2F%2F%2F%2Fp6enr6%2Bvt7e3v7%2B%2Fx8fHy8vLz8%2FP09PT29vb39%2Ff5%2Bfn8%2FPz9%2Ff3%2B%2Fv7%2F%2F%2F9qYR%2FuAAAAonRSTlMAAQECAgMDBAYGBwgKCwwMDQ4SEhQUGhwdHiIjIyQkJygpMDIzMzQ1NTY3OTo8PDw%2FP0ZITk9RUlNTVldXV1hYWlpaWltdYGBiY2ZpbHB1dXZ3d3t8fX5%2Ff4aHiIqKj5WXn6KjpKmssrK0t7u8vb7BwsPEyszNzc3O0dLT09fY2tvf4OXm5ufn6ers7O3w8fLy8vL09fX29%2Ff4%2Bvv7%2FP39%2Ff5qibsTAAABrElEQVR4AX2LhfcSURCFBxHBbkWxuwW7Q7AbQ7AbuwMMRQxRVAwMxRBWBRSX%2BRN%2F97y3y9ldlv3OmfPu3PkemfBsVbaQAwsrzPxnLrVh4huc65h3I8iGno9walyj6wzu9CIrVxk86YvU%2BxVS6SKZOP4D5ccxJJnxHtvnvdRk10sUlUVEJy4NFIV33d8S89P1JJj3GOfaDqQlG4%2BcX7tdlL6DKtr7UwgwuOwRdY85h08vuD1A5MFnGEgB7OlGkg0XZj5bPFXEcW91oQHj37Iu0uh%2BYNqXlZtFvKkLN%2FZ9g%2FJ7Qiep9JutjD25AiGpC0nqehZG4%2BEQaXQe%2BX3oUbNA1P8uFPWWTyqzPo2yCGDSAyj%2FT4ncZ%2F%2FzFgEs%2FwClQmDptvk2AtjJsht275C9QJqwevIxZ2ETf3UWrjBPdxR%2B7V6zykkYfY5ek0HIWIXx%2FGIQnowucC1mFmg4JlbTlngRoRw2CiBcRizGSZCoY8mHDEIoj1BPUJOUiiLr1wR%2FFo%2BaIiPeHIO0ENIMcl6yECig%2FqlNIUCtuIMKS5Sgm2xxRao4VyMuaos7qkQtvzsAWpTtdh6JoYQAAAAASUVORK5CYII%3D) http://iconmonstr.com/zip-15/

In the first case a different image is required for TGZ. In the other two the same can be used for both ZIP and TGZ. Both, left and right colors can be modified.

I'm having problems when trying to generalize this. To insert every other badge in the doc, we use shortcodes. We can do that because all of them are singular. However, with ZIP/TGZ we want a general/parameterized badge, so that we can reuse it. Furthermore, we want to insert them multiple times with different text and targets.

These are the versions we need now.

- ...releases/download/2017-03-01/ghdl-0.34-dev-llvm-3.8-2017-03-01-ubu1204.tgz
- ...releases/download/2017-03-01/ghdl-0.34-dev-llvm-3.5-2017-03-01-ubu1404.tgz
- ...releases/download/2017-03-01/ghdl-0.34-dev-llvm-2017-03-01-fed.tgz
- ...releases/download/2017-03-01/ghdl-0.34-dev-mcode-2017-03-01-fed.tgz
- ...releases/download/2017-03-01/ghdl-0.34-dev-mcode-2017-03-01-win32.zip

For example, for the first one, this would be the shortcode:

```
.. |SHIELD:travis-ci| image:: https://img.shields.io/badge/ZIP-ghdl--0.34--dev--llvm--3.8--2017--03--01--ubu1204-323131.svg?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2Ci...
   :target: https://github.com/tgingold/ghdl/releases/download/2017-03-01/ghdl-0.34-dev-llvm-3.8-2017-03-01-ubu1204.tgz
   :alt: Release ghdl-0.34-dev LLVM-3.8 2017-03-01 ubun1204 TGZ
```

Forgetting about `:alt` for now, and just focusing on `:image:` and `:target:`, I tried to use extlinks: https://docs.python.org/2/library/re.html

A single argument is accepted. Therefore, it is not possible to set both full URLs at the same time. However, we can relate one to the other through regexp. For example, if `#=0.34-dev-llvm-3.8-2017-03-01-ubu1204`, we could do something like:

```
https://img.shields.io/badge/TGZ-ghdl--re.sub('-.+', '--', #)-323131.svg?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2Ci...
https://github.com/tgingold/ghdl/releases/download/2017-03-01/ghdl-#.tgz
```
where `re.sub` is a Python function por pattern substitution: https://docs.python.org/2/library/re.html

I tried to add this to the extlinks in `conf.py`:

```
'ghdlrelzip': ('https://github.com/tgingold/ghdl/releases/download/2017-03-01/ghdl-%s.zip', 'https://img.shields.io/badge/ZIP-ghdl--'+re.sub('-.+', '--', '#')+'-323131.svg?style=flat&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAACE1BMVEUAAAAAAABcXFwAAACpqakAAABXV1cAAAAAAADAwMBYWFgAAACcnJxzc3MiIiKPj4%2FExMRaWlohISHo6OgbGxs5OTnMzMw9PT3AwMBWVlZkZGSGhoanp6eLi4vMzMyAgIC3t7eUlJSysrKNjY2Wlparq6uysrKlpaW1tbV6enqzs7PR0dGrq6uEhISwsLDFxcW9vb3Kysrg4OC8vLy3t7fPz8%2FDw8Ojo6OsrKzS0tLQ0NC9vb3ExMTm5ua9vb3Q0NChoaGsrKyurq7e3t7U1NSWlpaJiYmNjY3R0dG0tLSVlZXCwsK8vLzDw8Ph4eHk5OTW1tbW1tbm5ube3t7g4ODKysq3t7fOzs7f39%2FW1tbR0dHOzs7CwsLe3t7c3Nzn5%2BfW1tbq6urIyMjb29vW1tbe3t7X19fa2trb29vt7e3q6urHx8ft7e3k5OTh4eHPz8%2FV1dXT09Pm5ubh4eHg4ODm5ub9%2Ff3%2F%2F%2F%2F%2F%2F%2F%2Fk5OTp6enY2Njo6OjZ2dnn5%2Bfp6enc3Nzu7u76%2Bvr09PTk5OTw8PDn5%2Bf5%2Bfnf39%2Fq6urg4ODo6Ojk5OT4%2BPjm5ubm5ubs7Ozu7u76%2Bvrk5OTu7u739%2Ffq6urr6%2Bvx8fH6%2Bvrt7e34%2BPj6%2Bvr%2B%2Fv7s7Oz5%2Bfn%2B%2Fv7%2F%2F%2F%2Fp6enr6%2Bvt7e3v7%2B%2Fx8fHy8vLz8%2FP09PT29vb39%2Ff5%2Bfn8%2FPz9%2Ff3%2B%2Fv7%2F%2F%2F9qYR%2FuAAAAonRSTlMAAQECAgMDBAYGBwgKCwwMDQ4SEhQUGhwdHiIjIyQkJygpMDIzMzQ1NTY3OTo8PDw%2FP0ZITk9RUlNTVldXV1hYWlpaWltdYGBiY2ZpbHB1dXZ3d3t8fX5%2Ff4aHiIqKj5WXn6KjpKmssrK0t7u8vb7BwsPEyszNzc3O0dLT09fY2tvf4OXm5ufn6ers7O3w8fLy8vL09fX29%2Ff4%2Bvv7%2FP39%2Ff5qibsTAAABrElEQVR4AX2LhfcSURCFBxHBbkWxuwW7Q7AbQ7AbuwMMRQxRVAwMxRBWBRSX%2BRN%2F97y3y9ldlv3OmfPu3PkemfBsVbaQAwsrzPxnLrVh4huc65h3I8iGno9walyj6wzu9CIrVxk86YvU%2BxVS6SKZOP4D5ccxJJnxHtvnvdRk10sUlUVEJy4NFIV33d8S89P1JJj3GOfaDqQlG4%2BcX7tdlL6DKtr7UwgwuOwRdY85h08vuD1A5MFnGEgB7OlGkg0XZj5bPFXEcW91oQHj37Iu0uh%2BYNqXlZtFvKkLN%2FZ9g%2FJ7Qiep9JutjD25AiGpC0nqehZG4%2BEQaXQe%2BX3oUbNA1P8uFPWWTyqzPo2yCGDSAyj%2FT4ncZ%2F%2FzFgEs%2FwClQmDptvk2AtjJsht275C9QJqwevIxZ2ETf3UWrjBPdxR%2B7V6zykkYfY5ek0HIWIXx%2FGIQnowucC1mFmg4JlbTlngRoRw2CiBcRizGSZCoY8mHDEIoj1BPUJOUiiLr1wR%2FFo%2BaIiPeHIO0ENIMcl6yECig%2FqlNIUCtuIMKS5Sgm2xxRao4VyMuaos7qkQtvzsAWpTtdh6JoYQAAAAASUVORK5CYII%3D' )
```

and use it with:

```
:ghdlrelzip:`0.34-dev-llvm-3.8-2017-03-01-ubu1204`
```

But, this is the result:

```
https://img.shields.io/badge/ZIP-ghdl–#-323131.svg?style=flat&logo={long_image_code}0.34-dev-llvm-3.8-2017-03-01-ubu1204
```
The link URL is correct (well, should declare and use :ghdltgz: for this specific case), but the pattern substitution is not properly donde, since it is evaluated before the extlink adds the content. Well, that was expected. We can play with the [prefix](http://www.sphinx-doc.org/en/stable/ext/extlinks.html):

- If the prefix is None, the link caption is the full URL.
- If the prefix is the empty string, the link caption is the partial URL given in the role content (123 in this case.)
- If the prefix is a non-empty string, the link caption is the partial URL, prepended by the prefix – in the above example, the link caption would be issue 123.

Therefore, we can use this extlink:

```
'ghdlrelzip': ('https://github.com/tgingold/ghdl/releases/download/2017-03-01/ghdl-%s.zip', 'https://img.shields.io/badge/ZIP-ghdl--' )
```

And define a function which takes the output, and applies these filters:

```
Replace `(badge/ZIP-ghdl-)(.+)"`
with {\1}+re.sub('-.+', '--', {\2})+'"-323131.svg?style=flat&logo={long_image_code}'
```

@Paebbels is something like that possible? That is, to make Python run a function just after another one is finished. May be [defer](https://pythonhosted.org/defer/defer.html). Have you ever used it?

**Comment by Paebbels** [comment]
We could create our own shield directive derived from the image directive. Sphinx can load user plugins that define further directives and roles.
