### ISSUE TITLE
configure script aborts in MinGW, while comparing `srcdir`

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#362]
The `configure` script aborts execution with this error message:

```Bash
$ ../../configure
Cannot compute absolute source dir (or incorrect srcdir)
srcdir=../..
abs_srcdir=/c/git/GitHub/Paebbels/ghdl/build/mingw64-llvm40/../..
```

**Comment by Paebbels** [comment]
Argh. MinGW's base installation doesn't contain tools like:
- **cmd** => difftools
  installation command: `pacman -S msys/diffutils`
- **make** => make
  installation command: `pacman -S msys/make`

Is it possible to check if these tools exist before using them?
(And display the needed package name if known?)

**Comment by tgingold** [comment]
There are two different issues:

* configure on mingw:  I prefer to handle that by documentation
* fstapi.c on win64 -> this file comes from gtkwave, so maybe this was already fixed, or that's the place to fix it.

**Comment by Paebbels** [comment]
I have seen some configure scripts checking all preconditions. Are these configure scripts auto generated by one of the "auto" tools?

**Comment by Paebbels** [comment]
I wrote an email to the GTKwave mailing list. This was the answer:

> I looked at the source for `fstapi.c` found in gtkwave SVN and it uses `intptr_t` where the compiler is complaining. The GHDL codebase might need to be updated.

**Comment by tgingold** [comment]
I have updated fstapi.
