### ISSUE TITLE
Vendor library compile script failing if no output path is set (Power shell)

### ISSUE THREAD

**Issue by Elvegard** [tgingold/ghdl#363]
If the output directory is set to working directory, i.e. ".", the created directory structure will be incorrect and no files will be created.
The compile script will not report any errors and will report success when done.

**Comment by Paebbels** [comment]
@Elvegard Can you check this issue with the latest version? There were some big changes in the scripts. I also fixed some issues.

**Comment by Elvegard** [comment]
@Paebbels the output directories have been corrected in the latest version
