### ISSUE TITLE
Failing AppVeyor tests, but positive CI result

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#364]
Hello,

I have a build problem with my local MinGW, so I wanted to check the AppVeyor logs, but instead I found these problems for MinGW32 + mcode backend:
- [bug067 at line 2255](https://ci.appveyor.com/project/tgingold/ghdl/build/0.34-dev-267/job/f6pluqibjocycubh#L2255) - caused execption
- [bug071 at line 2292](https://ci.appveyor.com/project/tgingold/ghdl/build/0.34-dev-267/job/f6pluqibjocycubh#L2292) - failed
- [issue314 at line 3676](https://ci.appveyor.com/project/tgingold/ghdl/build/0.34-dev-267/job/f6pluqibjocycubh#L3676) - caused exception

**Comment by tgingold** [comment]
> Hello,
> 
> I have a build problem with my local MinGW, so I wanted to check the
> AppVeyor logs, but instead I found these problems for MinGW32 +
> mcode backend:
> 
>     * bug067 at line 2255 - caused execption

This one looks ok (note the status and --bug-box option).


>     * bug071 at line 2292 - failed

That's possibly a mscrt issue.  To be investigated but not critical.

>     * issue314 at line 3676 - caused exception

To be investigated.

Clearly the harness doesn't work on windows, as it doesn't report failures correctly.

Tristan.
