### ISSUE TITLE
elaboration error on Centos 7

### ISSUE THREAD

**Issue by stfarley** [tgingold/ghdl#408]
Hello,
I am running 0.33 on a Centos 7 machine.

I get the following error at elaboration time.

ghdl -e --std=08 tb
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
ghdl: compilation error

It seems like some sort of configuration issue but I am not sure what.

Thanks

**Comment by tgingold** [comment]
You just need to install the zlib-devel package.
yum install zlib-devel

Btw, ghdl 0.34 is now available.

Tristan

Envoyé avec AquaMail pour Android
http://www.aqua-mail.com

**Comment by stfarley** [comment]
Thanks Tristan,
That looked after it.
