### ISSUE TITLE
Compiling GHDL in debian Strech 9.1 and gcc 6.4

### ISSUE THREAD

**Issue by ellorens** [tgingold/ghdl#437]
Hi all, i'm trying to compile the GHDL package with GCC because i want to use the GCOV utility, and i think that is the only way to use it, my problem start when i try to compile the Xilinx Library Unisim, you can see the console output here 
`error:unisim-obj08.cf : bad library format`
I have succesfully installed GHDL compiling it with gcc but when i try to use thouse libraries all crash.

`ghdl -v
GHDL 0.35-dev (2017-03-01-252-g90f4fd21) [Dunoon edition]
 Compiled with GNAT Version: 6.3.0
 GCC back-end code generator`

**Comment by tgingold** [comment]
I suppose you have compiled unisim with a previous (and old) version of ghdl.
Remove that unisim-obj08.cf file, and re-analyze unisim.
