### ISSUE TITLE
Building with custom gnatmake

### ISSUE THREAD

**Issue by sonOfRa** [tgingold/ghdl#443]
My system doesn't have a gnatmake symlink, instead it only has the gnatmake-6.3.0 executable to indicate the gcc version. The configure script actually works properly when I set ``GNATMAKE=gnatmake-6.3.0 ./configure``. The top level makefile now has ``GNATMAKE=gnatmake-6.3.0``. However all the sub-makefiles (like https://github.com/tgingold/ghdl/blob/master/src/ortho/llvm/Makefile) still assume that the ``gnatmake`` is on the path, and then the build fails. I "fixed" it manually by adjusting the Makefiles, but I'm not sure if this could possibly be fixed so this becomes unnecessary in the future.

EDIT: The same also goes for gnatbind, which is just assumed to be present no matter what. I adjusted that in the local Makefiles as well.

**Comment by tgingold** [comment]
I have pushed a fix.  Tell me if this isn't complete.

**Comment by sonOfRa** [comment]
That looks to have done the trick. Thanks for the fast resolution!
