### ISSUE TITLE
v0.34 Name of the download files break Caskroom install file

### ISSUE THREAD

**Issue by Birate** [tgingold/ghdl#454]
The filename is **ghdl-v0.34-llvm-*** and the previous missed the leading "v" before the version's number; so the _[Hombrew/Caskroom ghdl's install file](https://github.com/caskroom/homebrew-cask/blob/b6136cdb2831a5905035b4d74cae5a3071d67034/Casks/ghdl.rb)_ isn't updatable.

We have IMO 2 solutions:
- stick with the leading "v" and update the caskroom's file
- remove the leading "v"

**Comment by tgingold** [comment]
You're right, let's remove the v before the version.  It brings nothing.
