### ISSUE TITLE
vendors compilation script fails on OSX 

### ISSUE THREAD

**Issue by bergnoli** [tgingold/ghdl#463]
in the shared.sh file there is no OSX workaround for using "greadlink" instead "readlink"

**Comment by tgingold** [comment]
If you can test a patch, I can merge it.

**Comment by bergnoli** [comment]
`diff --git a/libraries/vendors/shared.sh b/libraries/vendors/shared.sh
index 6b77b2f5..1c672fb1 100644
--- a/libraries/vendors/shared.sh
+++ b/libraries/vendors/shared.sh
@@ -76,7 +76,8 @@ SetupDirectories() {
        fi

        # Resolve paths to an absolute paths
-       SourceDirectory=$(readlink -f $SourceDirectory)
+       READLINK=readlink; if [[ $(uname) == "Darwin" ]]; then READLINK=greadlink; fi
+       SourceDirectory=$($READLINK -f $SourceDirectory)
        if [[ ! "$DestinationDirectory" = /* ]]; then
                DestinationDirectory=$WorkingDir/$DestinationDirectory
        fi`

**Comment by tgingold** [comment]
Thanks!
