### ISSUE TITLE
deb package has not gcc dependency

### ISSUE THREAD

**Issue by vermaete** [tgingold/ghdl#7]
I've just installed the 0.33 dep package (jessie, amd64) on a brand new Debian installation.  It looks like gcc is no dependency of the ghdl package.

**Comment by vermaete** [comment]
Forgot to add: I could not find the code to build the Debian package in this git repo.

**Comment by vermaete** [comment]
Just for the record:
zlib1g-dev was also missing for me.
'apt-get install zlib1g-dev'.
the zlib1g package itself wasn't enough.

**Comment by tgingold** [comment]
You're correct.  The code to build the Debian package is in the release.
(The release was made before moving to github, some pieces may be on source forge).

**Comment by jorisvr** [comment]
Thanks for the bugfix.
