### ISSUE TITLE
Embed vendor library compile scripts into binary packages for installation.

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#84]
I'm currently reworking the vendor library compile scripts for Linux (see #82). I'm filing this issue, so nobody forgets about this tasks (either you or me :) ).

The binary packages like `*.deb` should be extended to install these Bash scripts into the installation directories. I'm not sure where Linux distributions usually stores such scripts, which are not "binaries".

**Comment by tgingold** [comment]
I think this is automatically done once scripts are installed.
